/* ============================================================
   ZODIAC FIGHTERS — Lore extendido de las cartas
   globalThis.ZF_LORE[id] = texto más profundo (2-3 frases).
   Si una carta no tiene entrada aquí, se usa su descripción corta
   de spirits-data.js. Se puede ampliar por categorías sin romper nada.
   ============================================================ */
(function(G){
  G.ZF_LORE = {
    /* ---- Leyendas del Zodiaco ---- */
    l_gato: "Llegó tarde a la Gran Carrera porque la Rata lo adormeció con falsas promesas. Desde entonces vaga al margen de los doce, jurando que algún día su nombre figurará en el zodiaco. Su rencor es paciente; su zarpa, certera.",
    l_jade: "Soberano del cielo que convocó la Gran Carrera para ordenar el tiempo en doce signos. Su palabra es ley entre dioses y bestias. Pero incluso él teme el día en que el orden que creó deba renacer en otras manos.",
    l_qinglong: "Guardián del Este y heraldo de la primavera. Cuando despliega sus barbas, el viento obedece y la lluvia cae sobre los campos sedientos. Vela cada amanecer desde las nubes más altas del mundo.",
    l_zhuque: "Ave de fuego del Sur que arde para renacer. Cada verano se consume en sus propias llamas y regresa más radiante que antes. Donde cae su ceniza, la vida vuelve a brotar.",
    l_baihu: "Bestia del Oeste y señor del otoño. Su rugido dispersa a los demonios y su pelaje blanco anuncia la llegada de la justicia. Camina entre los muertos sin conocer el miedo.",
    l_xuanwu: "Guardián del Norte y del invierno: tortuga y serpiente entrelazadas en un solo cuerpo. Encarna la resistencia silenciosa y el conocimiento que sobrevive al paso de las eras.",
    l_qilin: "Bestia sagrada que solo se muestra ante los sabios y los gobernantes justos. Su paso no aplasta la hierba ni hiere a criatura alguna. Su aparición anuncia tiempos de fortuna.",
    l_nian: "Monstruo que cada Año Nuevo descendía a devorar aldeas, hasta que los hombres descubrieron su miedo al color rojo y al estruendo. Por eso aún hoy se encienden petardos y faroles en su contra.",
    l_yinyang: "El abrazo eterno de las fuerzas opuestas: luz y sombra, calma y furia. Ninguna existe sin la otra, y de su tensión constante nace todo cuanto se mueve en el universo.",
    l_sol: "El astro recortado que ilumina cada escenario de la contienda. Sencillo y constante, observa los combates desde lo alto sin tomar partido por nadie.",
    l_luna: "Vela por los duelos nocturnos del Lago Lunar. Su luz pálida alarga las sombras y vuelve más solemne cada golpe librado bajo el cielo callado.",
    l_wonejo: "La mascota maldita del estudio, mitad conejo, mitad augurio. Dicen que solo se revela ante los coleccionistas más obsesivos... y que, una vez visto, ya no vuelve a abandonarte.",

    /* ---- Planetas y Cosmos ---- */
    cos_0: "Una estrella enana amarilla que concentra el 99.8% de la masa del sistema solar. En su núcleo la fusión del hidrógeno alcanza 15 millones de grados y libera la energía que sostiene toda la vida en la Tierra.",
    cos_1: "El planeta más cercano al Sol y el más pequeño. Sin atmósfera que lo abrigue, pasa de 430 °C de día a -180 °C de noche; un año suyo dura apenas 88 días terrestres.",
    cos_2: "El 'lucero del alba', el planeta más brillante y caliente. Su densa atmósfera de CO₂ atrapa el calor hasta 465 °C, suficiente para fundir plomo; además gira al revés que los demás.",
    cos_3: "El único mundo conocido con vida. Tres cuartas partes son océano, y su campo magnético y su atmósfera lo protegen del viento solar. Desde el espacio es un punto azul pálido.",
    cos_4: "El planeta rojo, teñido por el óxido de hierro. Alberga el Olympus Mons, el volcán más alto del sistema solar, y antiguos cauces secos que hablan de ríos perdidos.",
    cos_5: "El gigante gaseoso, tan enorme que cabrían más de 1.300 Tierras dentro. Su Gran Mancha Roja es una tormenta más ancha que nuestro planeta que lleva siglos girando.",
    cos_6: "El señor de los anillos, formados por miles de millones de fragmentos de hielo y roca. Es tan poco denso que flotaría en el agua si existiera un océano lo bastante grande.",
    cos_7: "Un gigante de hielo que rota acostado, con sus polos casi apuntando al Sol. Su tono azul verdoso viene del metano, y cada estación suya dura unos 21 años.",
    cos_8: "El planeta más lejano, azul intenso y gélido. En él soplan los vientos más veloces del sistema solar, sobre 2.000 km/h. Fue el primero hallado por cálculo matemático antes de verlo.",
    cos_9: "Un mundo enano del cinturón de Kuiper, con un gran corazón helado de nitrógeno en su superficie. Tan lejano que su año dura 248 años terrestres.",
    cos_10: "El único satélite natural de la Tierra. Su gravedad gobierna las mareas y estabiliza el eje de nuestro planeta. Siempre nos muestra la misma cara.",
    cos_11: "El mayor cuerpo del cinturón de asteroides y el único planeta enano del sistema solar interior. Bajo su corteza podría esconder agua salada, y en sus cráteres brillan puntos blancos misteriosos.",
    cos_12: "Un planeta enano helado más allá de Plutón, tan masivo que su descubrimiento obligó a redefinir qué es un planeta. Tarda 557 años en dar una vuelta al Sol.",
    cos_13: "Una bola de hielo, polvo y roca que, al acercarse al Sol, despliega una cola luminosa de millones de kilómetros. Algunos regresan cada cierto tiempo, como el de Halley.",
    cos_14: "Roca errante sobreviviente de la formación del sistema solar. La mayoría orbita entre Marte y Júpiter; el impacto de uno grande pudo extinguir a los dinosaurios.",
    cos_15: "Una región donde la gravedad es tan intensa que ni la luz escapa. Nace del colapso de estrellas enormes y deforma el espacio y el tiempo a su alrededor.",
    cos_16: "La muerte explosiva de una estrella masiva, que por días puede brillar más que una galaxia entera. En esa explosión se forjan los elementos pesados que forman los planetas... y a nosotros.",
    cos_17: "Inmensas nubes de gas y polvo, cunas donde la gravedad enciende nuevas estrellas. Sus colores provienen de gases excitados por la luz estelar.",
    cos_18: "El faro más brillante del universo: el núcleo activo de una galaxia lejana, alimentado por un agujero negro supermasivo que devora materia y la hace resplandecer.",
    cos_19: "Nuestra galaxia espiral, hogar de más de 100.000 millones de estrellas. La franja lechosa del cielo nocturno es su disco visto desde dentro.",
    cos_20: "No es una estrella, sino un meteoro: un grano de polvo que arde al rozar la atmósfera. Las lluvias de estrellas ocurren cuando la Tierra cruza la estela de un cometa.",
    cos_21: "Una isla cósmica de miles de millones de estrellas, gas y polvo unidos por la gravedad. El universo observable contiene billones de ellas.",
    cos_22: "Una estrella de neutrones que gira a gran velocidad y emite pulsos de radiación como un faro. Tan densa que una cucharada de su materia pesaría miles de millones de toneladas.",
    cos_23: "Cortinas de luz en los cielos polares, nacidas cuando partículas del Sol chocan con la atmósfera. El verde viene del oxígeno; el rojo y el violeta, de capas más altas.",
    cos_24: "El instante en que un astro oculta a otro. En un eclipse solar la Luna tapa al Sol y revela su corona: un raro alineamiento que dura solo minutos.",
    cos_25: "La mayor luna de Saturno y la única con atmósfera densa. En su gélida superficie corren ríos y lagos... pero de metano líquido en lugar de agua.",
    cos_26: "Luna helada de Júpiter que esconde bajo su corteza un océano de agua salada, quizá con más agua que toda la Tierra. Uno de los lugares más prometedores para buscar vida.",
    cos_27: "La luna más volcánica del sistema solar. La feroz gravedad de Júpiter la amasa por dentro, lanzando penachos de azufre a cientos de kilómetros de altura.",
    cos_28: "La mayor de las dos lunas de Marte, con forma de papa. Orbita tan cerca que cada siglo se acerca un poco más; algún día se romperá formando un anillo.",
    cos_29: "Una masa invisible que no emite luz, pero cuya gravedad sostiene unidas a las galaxias. Constituye la mayor parte de la materia del universo, y aún nadie sabe qué es.",

    /* ---- Gemas y Minerales ---- */
    gem_0: "El mineral natural más duro que existe: carbono puro cristalizado bajo enorme presión a cientos de kilómetros bajo tierra. Tarda miles de millones de años en formarse y dispersa la luz en destellos de arcoíris.",
    gem_1: "Variedad roja del corindón, teñida por el cromo. Tan dura que solo el diamante la supera; los ejemplares de rojo 'sangre de paloma' pueden valer más que el oro.",
    gem_2: "El corindón en todos sus colores salvo el rojo, aunque el azul es el más célebre. Símbolo de sabiduría y nobleza, ha adornado coronas reales durante siglos.",
    gem_3: "Berilo verde teñido por cromo y vanadio, apreciado ya por Cleopatra. Casi siempre lleva 'jardines': inclusiones internas que delatan su origen natural.",
    gem_4: "Cuarzo violeta cuyo color nace de la irradiación y trazas de hierro. Los griegos creían que protegía de la embriaguez; su nombre significa 'no ebrio'.",
    gem_5: "Mineral de flúor y aluminio que va del dorado al azul. El topacio imperial, de tono naranja-dorado, fue el más codiciado por la realeza.",
    gem_6: "No es un cristal, sino sílice con agua cuyas microesferas difractan la luz en un 'juego de colores' único en cada piedra. Australia produce casi todo el del mundo.",
    gem_7: "La única joya creada por un ser vivo: un molusco que recubre un intruso con capas de nácar. No necesita tallado; nace ya pulida y luminosa.",
    gem_8: "Piedra sagrada de China, símbolo de pureza y virtud. Bajo el nombre se esconden dos minerales, jadeíta y nefrita, ambos tan tenaces que resisten el martillo.",
    gem_9: "Una de las primeras gemas extraídas por el hombre, azul celeste por el cobre. Amuleto protector de egipcios, persas y pueblos nativos americanos.",
    gem_10: "Familia de minerales que va del rojo profundo al verde. Tan duro y abundante que también sirve de abrasivo; símbolo de vitalidad y constancia.",
    gem_11: "Berilo azul como el mar; según la leyenda, tesoro de las sirenas. Los marineros la llevaban como amuleto contra los naufragios.",
    gem_12: "Una de las pocas gemas de un solo color, verde oliva por el hierro. Nace en el manto terrestre... y también se ha hallado dentro de meteoritos.",
    gem_13: "Cuarzo amarillo a dorado, 'la piedra del comerciante' por asociarse a la prosperidad. La mayoría es en realidad amatista tratada con calor.",
    gem_14: "El mineral más común de la corteza terrestre y uno de los más útiles. Vibra a una frecuencia exacta: por eso mueve relojes y aparatos electrónicos.",
    gem_15: "Vidrio volcánico nacido de lava enfriada tan rápido que no llegó a cristalizar. Sus bordes pueden ser más afilados que un bisturí; los antiguos la usaban como cuchillo.",
    gem_16: "Roca azul ultramar salpicada de pirita dorada. Molida, dio el pigmento más caro del Renacimiento; los faraones la enterraban con sus muertos.",
    gem_17: "Mineral de cobre con hipnóticas bandas verdes concéntricas. Molida fue sombra de ojos en Egipto y pigmento de pintores durante siglos.",
    gem_18: "Resina de árboles fosilizada durante millones de años. A veces atrapa insectos o plantas, conservando una cápsula viva de un pasado remoto.",
    gem_19: "Variedad de ágata de bandas negras, símbolo de firmeza y protección. Tallada en camafeos y sellos desde la antigüedad.",
    gem_20: "Ni piedra ni planta, sino el esqueleto calcáreo de diminutos animales marinos. Apreciado como joya, hoy se protege por la fragilidad de los arrecifes.",
    gem_21: "Descubierta en 1967 al pie del Kilimanjaro, es mil veces más rara que el diamante y solo existe en un rincón de Tanzania. Cambia del azul al violeta según la luz.",
    gem_22: "La gema camaleón: verde a la luz del día, roja bajo luz cálida. Tan escasa que los ejemplares finos superan al diamante en precio.",
    gem_23: "Durante siglos se confundió con el rubí; el 'Rubí del Príncipe Negro' de la corona británica es en realidad una espinela. Brilla en rojos, rosas y azules.",
    gem_24: "Berilo rosa por trazas de manganeso, bautizado en honor al banquero J. P. Morgan. Su tono suave la hizo favorita en la joyería moderna.",
    gem_25: "Calcedonia verde oscura con motas rojas que parecen gotas de sangre. En la Edad Media se le atribuían poderes curativos.",
    gem_26: "Calcedonia de cálido naranja a rojizo, teñida por óxido de hierro. Los antiguos la grababan como sello porque la cera caliente no se le pegaba.",
    gem_27: "Famosa por su luminiscencia: el fenómeno de la 'fluorescencia' lleva su nombre. Aparece en casi todos los colores, a veces varios en un mismo cristal.",
    gem_28: "El 'oro de los tontos': su brillo metálico dorado engañó a muchos buscadores. En realidad es sulfuro de hierro, y al golpearla suelta chispas.",
    gem_29: "Óxido de hierro de brillo metálico y raya rojiza; su nombre viene del griego 'sangre'. Pesada y fría, fue espejo y pigmento desde la prehistoria.",
    gem_30: "Variedad transparente del yeso, blanca y nacarada como la luz lunar a la que debe su nombre (Selene). Tan blanda que se raya con la uña.",
    gem_31: "De aspecto gris apagado hasta que, al moverla, estalla en destellos azules y dorados: un efecto óptico llamado 'labradorescencia'.",
    gem_32: "Rosa con bandas blancas que recuerdan los anillos de un árbol. Es la piedra nacional de Argentina, formada en antiguas minas incas.",
    gem_33: "Azul profundo veteado de blanco, parecida al lapislázuli pero sin pirita. Mineral de la lógica y la calma mental según la tradición.",
    gem_34: "Cuarzo verde salpicado de diminutas escamas brillantes (aventurescencia). Considerada piedra de la suerte y la oportunidad.",
    gem_35: "Uno de los minerales más comunes y con más formas cristalinas. La variedad transparente, 'espato de Islandia', duplica las imágenes que se ven a través de ella.",
    gem_36: "La familia que reúne a la esmeralda (verde), la aguamarina (azul) y la morganita (rosa): el mismo mineral con distintas trazas de color.",
    gem_37: "Su fuego y brillo rivalizan con el diamante, por lo que se usó como imitación. Algunos cristales están entre los materiales más antiguos de la Tierra: 4.400 millones de años.",
    gem_38: "Espodumena de color rosa lila, descubierta a inicios del siglo XX. Su tono puede desvanecerse con el sol, por lo que se le llama 'gema de la noche'.",
    gem_39: "Una pectolita azul caribeña que solo se halla en un punto de la República Dominicana. Sus ondas recuerdan el mar y el cielo del trópico.",
    gem_40: "Curiosamente, es el mismo mineral que forma tus dientes y huesos. Como gema brilla en azules y verdes vivos, aunque es bastante blanda.",
    gem_41: "Mineral de cobre de un azul verdoso vibrante, a menudo entrelazado con cuarzo. Acompañó a los pueblos andinos como piedra de serenidad.",
    gem_42: "La piedra del amor por excelencia, de un rosa lechoso por trazas de titanio. Su color suele ser tenue y luce mejor en piezas grandes.",
    gem_43: "Feldespato verde azulado que toma su nombre del río Amazonas, aunque allí no se encuentra. Símbolo de esperanza y de la palabra sincera."
  };
})(typeof globalThis!=='undefined'?globalThis:window);
